### ISSUE TITLE
Linking PR title on the page

### ISSUE THREAD

**Issue by Techn1x** [jefgen/github-jira-linkifier-webextension#3]
I would find this most helpful - on the PR page, linking the issue number to the Jira ticket

![Screen Shot 2019-06-25 at 9 06 11 am](https://user-images.githubusercontent.com/1049837/60057607-8bb6a680-9728-11e9-8033-2d411f198b2e.png)

![Screen Shot 2019-06-25 at 9 07 23 am](https://user-images.githubusercontent.com/1049837/60057653-aee15600-9728-11e9-8c47-bfd20cb45fc7.png)

**Comment by Techn1x** [comment]
Was just looking through the code and noticed that you do have code for this, so clearly it's not working for me for some reason...

https://github.com/jefgen/github-jira-linkifier-webextension/blob/master/src/background.js#L63-L74

**Comment by Techn1x** [comment]
I think the problem is this line;
https://github.com/jefgen/github-jira-linkifier-webextension/blob/master/src/background.js#L67

When I call `document.getElementsByClassName('js-issue-title')` I get 2 elements
![Screen Shot 2019-06-25 at 9 16 02 am](https://user-images.githubusercontent.com/1049837/60057976-e4d30a00-9729-11e9-9d5c-b3fb52f25981.png)

The second occurrence of the element is just a link to the top of the page, and can probably be ignored. So maybe just do all elements with classname 'js-issue-title' that are not already links.

If I get some time I'll put a PR together but feel free to beat me (I've never developed a Firefox extension before so I have no idea how to test any changes I make)

**Comment by jefgen** [comment]
Thanks for reporting this issue, and for debugging the problem!

I think I'll change the code to only look for the `span` element, which would also avoid possibly creating nested links (nested "a" elements), as it looks like the second element is hidden on the GitHub PR page.

**Comment by jefgen** [comment]
I pushed an updated version of the extension (1.0.4) to the Mozilla Add-ons site.
Try checking for updates and let me know if it fixes your issues.
Thanks!

**Comment by Techn1x** [comment]
Works well, thanks for that!

For what it's worth, the `a` element isn't hidden on the page, if you have a longer PR and you scroll down the page it shows up at the top of the page in a small header - but it's probably not worth worrying about

![Screen Shot 2019-06-25 at 6 25 55 pm](https://user-images.githubusercontent.com/1049837/60082244-b0d20600-9776-11e9-95d1-0dd2334a8fd2.png)
