### ISSUE TITLE
seeing render issues just recently

### ISSUE THREAD

**Issue by dfuentes77** [jefgen/github-jira-linkifier-webextension#7]
Screenshot attached

<img width="1020" alt="Screen Shot 2020-02-07 at 1 04 58 AM" src="https://user-images.githubusercontent.com/942484/74015703-f8905100-4945-11ea-924f-10c1f3eba183.png">

**Comment by jefgen** [comment]
Thanks for reporting this issue! I'm also seeing the problem as well.
I've make a fix here PR #8, and will push out an update shortly.
Thanks!

**Comment by dfuentes77** [comment]
awesome, thanks for the quick turn around.  That fixed it.
